### ISSUE TITLE
Error when running Resonator Flux - qw5q_platinum

### ISSUE THREAD

**Issue by L4VM4T** [qiboteam/qibolab#1126]
Hi, 

I am encountering the following error when running the Resonator Flux. I am working on the qw5q_platinum chip.
[_qw5q_platinum_latest.json](https://github.com/user-attachments/files/18259913/_qw5q_platinum_latest.json)

**Comment by stavros11** [comment]
Thanks for reporting this. Could you provide the action runcard and configuration (platform, versions, etc.) that caused this so that I can try to reproduce? 

I tried the following:
```yaml
platform: qw5q_platinum

targets: [0, 1, 2, 3, 4]

actions:

    - id: resonator flux dependence
      operation: resonator_flux
      parameters:
          freq_width: 10_000_000
          freq_step: 50_000 # 100_000
          bias_width: 0.6 # 0.8
          bias_step: 0.01
          nshots: 1024
          relaxation_time: 5000
```
and it worked for me, resulting to this report http://login.qrccluster.com:9000/_po2kOx0TIu8iivMfn9SOg==, which looks fine.
