### ISSUE TITLE
Error with `chevron` acquisition

### ISSUE THREAD

**Issue by ElStabilini** [qiboteam/qibolab#1147]
During the past week, I have faced the following problem multiple times while trying to run the `chevron` protocol.

The runcard I tried to run is the following:
```
platform: qw11q

targets: [ [B2, B4] ]

actions:

  - id: chevron CZ

    operation: chevron
    parameters:
      amplitude_min: -0.49
      amplitude_max: -0.43
      amplitude_step: 0.002
      duration_max: 120
      duration_min: 0
      duration_step: 1
      native: CZ
      nshots: 256
      relaxation_time: 100000

```

I was working on commit https://github.com/qiboteam/qibolab/commit/0f0e582c, branch `test_cryoscope_postprocessing` (which points to 0.2) of `qibocal`, and a `qibolab_platform_qrc` branch with fir filters obtained with cryoscope and pointing to `b_line_rererererecal-0.2`.

The protocol fails during acquisition with the output in the attached file.

[slurm-734018.txt](https://github.com/user-attachments/files/18809624/slurm-734018.txt)

As @alecandido suggested I report here also the following objects (printed also in the slurm output`)

- `ro_low.id`:  `139818938987152`
- `results`: `{139818938987152: None, 139818938987472: None}`

Maybe it is also useful to say that the acquisition works correctly at least in the amplitude interval [0.5, -0,2) which I completely scanned by performing multiple chevron protocols on sub-intervals.
 
My get-around for the problem was to move to the most recent commit of `qibolab`.
