### ISSUE TITLE
Qblox: Update of mixer phase and gain ratio parameters

### ISSUE THREAD

**Issue by jevillegasdatTII** [qiboteam/qibolab#1163]
Hey! The current drivers (v0.1) update only the offsets (I and Q) of the mixer, which is useful to suppress the LO leakage, but do not update the gain ration and phase offset of the sequencers used, which allows to also suppress the image frequency. In QBlox this corresponds to the `mixer_corr_gain_ratio` and `mixer_corr_phase_offset_degree` parameters. And this applies to both QRM and QCM modules. An option to this in v0.1 for the QRM module is in https://github.com/qiboteam/qibolab/commit/7ca32a8689c0fdb01ee0796d71b78de7a497a286 , using the "mixer_readout_phi" and "mixer_readout_g" parameters in the platform specification.

e.g.
```yaml
 "characterization": {
        "single_qubit": {
            "0": {
                ...
                "mixer_drive_g": 1.0,
                "mixer_drive_phi": 0.0,
                "mixer_readout_g": 1.04,
                "mixer_readout_phi": 15.73
            },
      }
}
```

Can this be taken into consideration for the drivers in `v0.2`, and can we use as a current solution something like the commit referenced?

Some prior discussion about this is in #900.
