### ISSUE TITLE
Duration sweeper for flux pulses not working

### ISSUE THREAD

**Issue by maxhant** [qiboteam/qibolab#462]
Hi,
I would like to report an issue on the Zurich driver sweeper for FluxPulse.

I have writen a routine for the IQM couplers that one can run with the following actions, and with `qibolab/maxim/iqm` and `qibocal/maxime/iqm`:
```yml
platform: iqm5q

qubits: [3]

format: csv

actions:

  - id: coupler_cz_flux_time
    priority: 0
    operation: coupler_cz_flux_time
    # main: coupler_swap
    parameters:
      amplitude_factor_min: -0.6
      amplitude_factor_max: -0.3
      amplitude_factor_step: 0.005 # 0.01
      duration_min: 40
      duration_max: 400
      duration_step: 2
      nshots: 1000
```

I have plugged in the oscilloscope to have a look at the pulses being swept. 

First, the routine is equivalent to the Chevron CZ, but sending the FluxPulse to the coupler instead:
![image](https://github.com/qiboteam/qibolab/assets/52139175/e153dfd6-5012-48f8-a6fd-6926bc97ce6a)

Here is a video of the pulse being swept in amplitude, and as you can see the duration does not move. It stays at the minimum value given, 40ns.
https://tiiuae.sharepoint.com/:v:/s/QuantumComputing/EegyXuELQPxHp2JlNxYzS8wBU1AeR_T-QbOSd_xIp3UukQ?e=bcEJk3

It would be great to have this resolved as it is the second last step to have a CZ. As you can see below, the CZ phase difference is changing as the coupler is moved. This was done for a fixed coupler duration. 
 
![image](https://github.com/qiboteam/qibolab/assets/52139175/843ff0f4-903e-4661-a276-f36724e12a9b)
