### ISSUE TITLE
Error performing zeno (main) on iqm

### ISSUE THREAD

**Issue by Edoardo-Pedicillo** [qiboteam/qibolab#625]
The parameters of the routines are (I ran the routine only for testing):
```yaml
    - id: zeno
      priority: 0
      operation: zeno
      parameters:
          readouts: 20
          nshots: 200
```
I got this error:
>"laboneq/controller/devices/device_shfqa.py", line 848, in _integrator_has_consistent_msd_num_state
    raise LabOneQControllerException(
laboneq.controller.util.LabOneQControllerException: Multi discrimination configuration of experiment is not consistent. Received num weights=20, num thresholds=1, where num_weights should be n-1 and num_thresholds should be (n-1)*n/2 with n the number of states.
