### ISSUE TITLE
Bugs when sweeping drive pulses parameters in qblox driver  with `AveragingMode.SINGLESHOT`

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibolab#637]
I found two bugs while running new protocols developed in https://github.com/qiboteam/qibocal/pull/567:

1. `rabi_amplitude`

The error triggered is the following

```sh
RecursionError: maximum recursion depth exceeded in comparison
```

2. `rabi_length`

Here is an example of a runcard:
```yml

platform: qw5q_gold_qblox

qubits: [0,1,2,3,4]

actions:

  - id: rabi
    priority: 0
    operation: rabi_length
    parameters:
      pulse_duration_start: 10
      pulse_duration_end: 200
      pulse_duration_step: 4
      pulse_amplitude: 0.5
      relaxation_time: 100_000
      nshots: 1024
```
In this case I see a single value in the plot:

![image](https://github.com/qiboteam/qibolab/assets/49183315/3123ece7-245e-41ec-b391-83fa327c4f22)
