### ISSUE TITLE
qblox sweeping problem

### ISSUE THREAD

**Issue by biankawolo** [qiboteam/qibolab#830]
Dear Qibo team. I am running spinq10q on qblox. The routine is  qubit spectroscopy. My action runcard is:   
```yaml
- id: QUBIT WIDE
    priority: 0
    operation: qubit_spectroscopy
    parameters:
      freq_width: 50_000_000
      freq_step: 100_000
      drive_duration: 2_000
      drive_amplitude: 0.05
      nshots: 3_000
      relaxation_time: 2000
```
I am on freshly pulled qibolab and qibocal. I get the following error:
```py
  File "/nfs/users/bianka.woloncewicz/qibolab/src/qibolab/instruments/qblox/controller.py", line 442, in _sweep_recursion
    if any(s.parameter not in rt_sweepers for s in sweepers):
RecursionError: maximum recursion depth exceeded. 
```

All the parameters I' m using are physically reasonable. It looks like a sweeper problem. When I dramatically reduce the freq_width to 10^6Hz it works in the sense that I don\t get the error, but I don\t see the qubit either. Also if I reduce the freq_width BUT increase the freq_step I get the same error.  Please help. Let\s save the qubits together.
